#first stage of building angular image
FROM node:alpine3.14 as build
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY . /app/    
RUN npm run build --prod
#final stage
FROM nginx:alpine
COPY --from=build /app/dist/Evaluation_FRONTEND /usr/share/nginx/html



# Step 2: Use a lightweight Nginx image to serve static files
FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
# Copy the production build generated by Vite from the previous stage
COPY --from=builder /app/build /usr/share/nginx/html
# Expose the port where the application will run
EXPOSE 5173
# Start Nginx to serve the application
ENTRYPOINT [ "nginx" , "-g" , "daemon off;" ]